### ISSUE TITLE
How to resume download

### ISSUE THREAD

**Issue by salioudiabate** [ayz4sci/DownloadProgress#2]
How to resume download after having left the screen ?

**Comment by ayz4sci** [comment]
The download is handled by DownloadManager not this library. 
The DownloadManager is a service that runs in the background.
Try to read more about DownloadManager service

**Comment by salioudiabate** [comment]
I mean the view that shows the progress of the download , it is managed by the library .
I want to know how I can redisplay the view ( the view from the library) after exit.

**Comment by ayz4sci** [comment]
To handle resume, simply call the show method and pass the required parameters to it.

downloadProgressView.show(downloadID, new DownloadProgressView.DownloadStatusListener() {
  @Override
  public void downloadFailed(int reason) {
     //Action to perform when download fails, reason as returned by DownloadManager.COLUMN_REASON
  }

  @Override
  public void downloadSuccessful() {
    //Action to perform on success
  }

  @Override
  public void downloadCancelled() {
    //Action to perform when user press the cancel button
  }
});
