### ISSUE TITLE
java.lang.ArithmeticException: divide by zero

### ISSUE THREAD

**Issue by handysofts** [ayz4sci/DownloadProgress#5]
Dear Developer,

There is an issue as below:

java.lang.ArithmeticException: divide by zero
    at com.ayz4sci.androidfactory.DownloadProgressView$2.run(DownloadProgressView.java:185)

Could you please solve it asap?
Thanks

**Comment by aakashbh2** [comment]
getting same error

**Comment by ayz4sci** [comment]
Resolved.
